name: Deploy to S3

on:
  push:
    branches:
      - main  # or any other branch
    tags:
      - 'v*'  # This is to trigger deployment on version tags like v1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use AWS_REGION Secret
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Using AWS_REGION"
          # Use the AWS_REGION in a command without directly echoing it
          aws configure set region $AWS_REGION    
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Install Dependencies
        run: npm install

      - name: Build
        env: 
          VITE_API_ADDR: ${{ secrets.VITE_API_ADDR }}
        run: npm run build

      - name: Zip Build Directory
        run: zip -r build-${{ github.ref_name }}.zip dist/

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}  # Using the AWS region secret
          SOURCE_DIR: 'dist'

      - name: Upload Build Zip for Version Control
        uses: actions/upload-artifact@v2
        with:
          name: build-archive
          path: build-${{ github.ref_name }}.zip
